// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3MIEAkzvpnhY2k0ntO6gixbMezEGtdEA',
    appId: '1:388818401538:web:cfc5ea2abfc8fa2920ea1b',
    messagingSenderId: '388818401538',
    projectId: 'busync-6b784',
    authDomain: 'busync-6b784.firebaseapp.com',
    storageBucket: 'busync-6b784.appspot.com',
    measurementId: 'G-GP8RY36QRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu0R_6icsVmZ2tFzpYYuU6Te6R2bCTnB0',
    appId: '1:388818401538:android:dfead03d0e020fd720ea1b',
    messagingSenderId: '388818401538',
    projectId: 'busync-6b784',
    storageBucket: 'busync-6b784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3stXyg-sMDeBxG1YBcvHrmWwMmJfD3U',
    appId: '1:388818401538:ios:2f3298d106d0a38c20ea1b',
    messagingSenderId: '388818401538',
    projectId: 'busync-6b784',
    storageBucket: 'busync-6b784.appspot.com',
    iosBundleId: 'com.example.busync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3stXyg-sMDeBxG1YBcvHrmWwMmJfD3U',
    appId: '1:388818401538:ios:0d6e39e58dc6a95820ea1b',
    messagingSenderId: '388818401538',
    projectId: 'busync-6b784',
    storageBucket: 'busync-6b784.appspot.com',
    iosBundleId: 'com.example.busync.RunnerTests',
  );
}
